services:
  fx-lessons:
    build:
      context: .
      dockerfile: Dockerfile
    image: fx-lessons:latest
    container_name: fx-lessons-ambient-occlusion
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - fx-network
    volumes:
      - ./logs:/var/log/nginx:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fx-lessons.rule=Host(`localhost`)"
      - "traefik.http.services.fx-lessons.loadbalancer.server.port=80"

networks:
  fx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16